# Optional Render manifest (template). You can push this file to your repo and
# use Render's "Infrastructure as Code" feature to create the service.

services:
  - type: web
    name: canteen-management-system
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    region: oregon
    autoDeploy: true
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: "<REPLACE_WITH_YOUR_MONGODB_URI>"
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
